# Copyright (C) 2012, Parrot Foundation.

=head1 PDD XX: M1 Design and Implementation Spec

=head2 Abstract

M1 refers to a C-like language targeting the M0 "virtual machine". That is,
M0 can be considered as a virtual machine which defines an instruction set
and a computation model. Details of M0 can be found in [1].

The M1 compiler is reentrant, which means it is thread-safe. This allows to 
invoke the M1 compiler if it's already running.

=head2 Status

See the TODO file for the current status.

=head2 Design Principles of M1

A few basic design principles (so-called I<key drivers>) drove the design
of M1:

=over 4

=item * Maintainability

=item * High-quality output (i.e., M0 instructions)

=item * Extensibility (e.g., easy to add another phase to the compilation process)

=item * Ease of implementation 

=back

=head3 Differences with C

Compared to C, M1 has:

=over 4

=item * a built-in C<string> type;

=item * a built-in C<bool> type;

=item * a C++-class-style construction for defining PMCs, including inheritance;

=item * a simpler (and more restrictive) grammar;

=item * no union construct {{XXX do we want that?}}

=item * no C<goto> statement (to prevent spaghetti code)

=item * namespaces {{XXX do we want that?}}

=item * a try-catch statement {{XXX if we get that working}}

=item * nested multi-line comments (/* comment 1 /* nested comment */ comment 1 part 2 */ )

=back

Other differences with C include the following.


=head2 M1 Milestones

Completed milestones:

=over 4

=item * assignments

=item * iterating statements (while, do-while, for)

=item * conditional statements (if/else, switch)

=item * one-dimensional arrays; read and write

=item * simple structs; read and write

=item * function calls and returns

=back

Incomplete milestones:

=over 4

=item * Enumerations

=item * PMC definitions

=item * methods (as part of a PMC)

=item * vtable methods (virtual methods)

=item * PMC inheritance

=item * namespaces

=item * semantic checker

=item * module system (preprocessor?)

=item * register allocator

=item * optimization phase

=back

=head2 Architecture overview

The M1 compiler follows the so-called C<batch-sequential> architecture> [2], which
is a variant of the better known C<pipes-and-filters> architectural pattern. The
key difference is that in a pipes-filter architecture, the next filter can already
start processing before the filter before it has finished. In the M1 compiler, all
text needs to be parsed before semantic analysis and other phases can start.

Each phase of the compiler is one "filter". The M1 compiler has the following phases:

=over 4

=item 1. Lexical and grammatical analysis (combined, as is usual for compilers).

=item 2. Semantic analysis/type checking.

=item 3. Instruction generation.

=item 4. Optimization and register allocation.

=item 5. File generation (writing instructions to an M0 file).

=back

Lexical analysis refers to the tokenization of the input file. Grammatical analysis
refers to parsing the input stream of tokens. The compiler invocation starts
with the grammar, which requests tokens from the lexer as needed until end of file
is reached. During the parse, an Abstract Syntax Tree (AST) is constructed for
later phases.

After the parse, the AST is passed on to the semantic analysis phase. In this phase,
the compiler performs a number of type checks.

After the type checking phase, the code generation phase traverses the AST, and
generates appropriate instructions for each node. 



=head2 Implementation

M1 is implemented in C. The lexer is implemented using the Flex lexer generator. 
The parser is implemented using the Bison parser generator. Flex and Bison are
more modern implementations of the well-known Lex and Yacc tools, respectively.
The choice for these tools is grounded in the fact that the precise definition 
of M1 was expected to be in flux in this early stage, and the need for maintainability.

The current implementation consists currently of about 8,000 lines of code, using 
SLOCcount [3], though it is expected this will go up to 10,000 when the implementation 
is finished.

The implementation consists of the following files:

=over 4

=item m1.l - lexer specification.

=item m1.y - parser specification.

=item ast.{c,h} - abstract syntax tree nodes definitions and constructors.

=item eval.{c,h} - code to generate M1 code from the AST. This is to ensure that the compiler
can generate the same code as it has parsed.

=item semcheck.{c,h} - implementation of the semantic check phase.

=item instr.{c,h} - structures and code to represent M0 instructions.

=item decl.{c,h} - structures and code to represent type declarations {{XXX needs better name}}

=item gencode.{c,h} - code generation.

=item stack.{c,h} - implementation of a stack

=item symtab.{c,h} - symbol table implementation.

=item ann.h - code annotation #defines for splint. {{XXX needs better name}}

=back

=head3 Type declarations

M1 has a number of built-in types. These are:

=over 4

=item * int

=item * num

=item * string

=item * char

=item * bool

=back

Besides these built-in types, M1 supports the notion of aggregate types; you can
define a C<struct>, which is essentially the same as a C struct, in which all attributes
(member fields) are publicly accessible. An M1 struct is therefore just a means to 
bundle a number of related variables.

Besides structs, M1 allows you to write PMCs. A PMC is a Parrot Magic Cookie, or
Poly-Morphic Container. The PMC is the magic means through which Parrot supports
language-dependent behavior. A PMC can be compared to a C++ class definition.

{{XXX need to see whether inheritance and vtables can be implemented.}}

=head3 Variable declarations

=head3 Assignments

=head3 Arrays

Arrays, when declared, are auto-vivivied. This means that code is generated to 
allocate memory for them. For instance, the following declaration:

 int x[10]; 
 
will allocate 10 * sizeof(int) bytes on the heap. 

=head3 Structs


=head3 User-defined type definitions

=head2 Subsystems

This section describes a number of subsystems and how they work.

=head3 Variables, Symbols and Registers


=head3 Register allocation and de-allocation

M1 has a nifty register allocation system. Three functions are the core of this
system:

 void alloc_reg(M1_compiler *c);
 void free_reg(M1_compiler *c, m1_reg r);
 void freeze_reg(M1_compiler *c, m1_reg r);
 



=head2 M1 Language Specification

=head3 M1 Lexical specification

The following words are reserved and cannot be used as identifier:

 bool
 break
 case
 char
 const
 continue
 default
 do
 else
 false
 for 
 if
 int
 null
 num
 pmc
 return
 string
 struct
 switch
 true
 while

=head3 M1 Grammar

The grammar of M1 is expressed using EBNF notation below. Note that this EBNF notation
differs from the Bison specification, as Bison expects a certain formatting of the
grammar rules.

M1-program: chunk+

chunk: function-def
     | pmc-def
     | struct-def
     | enum-def
     | namespace
     
struct-def: struct NAME { struct-member+ }      

struct-member: type NAME ;

function-def: type NAME ( parameters? ) block

parameters: parameter [, parameter]*

parameter: type NAME

enum-def: enum NAME { enum-constant [, enum-constant]* }

enum-constant: NAME
         
block: { statement* }    

statement: assignment
         | if-stat
         | while-stat
         | do-while-stat
         | break-stat
         | for-stat
         | switch-stat
         | return-stat
         | funcall-stat
         | block
         | var-decl
         | const-decl
         
assignment: target assignop expression ;

assignop: = | += | -= | *= | /= | %= | >>= | <<= | &= | |=

if-stat: if ( expression ) statement [else statement]?

while-stat: while ( expression ) statement

do-while-stat: do { statement* } while ( expression ) ;

for-statement: for ( for-init? ; for-cond? ; for-step? ) statement

break-stat: break

switch-stat: switch ( expression ) { case* default-case? }

case: case INTEGER : statement*

default-case: default : statement *
  
return-stat: return expression? ;

funcall-stat: funcall ';'

funcall: NAME ( arguments? )

arguments: argument [, argument]*

argument: expression
              
expression: INTEGER
          | NUMBER
          | STRING
          | CHAR
          | true
          | false
          | null
          | new NAME ( arguments? )
          | expression ? expression : expression
          | expression binop expression
          | unop expression
          | funcall
          | target
          | target ++
          | target --
          | ++ target
          | -- target
          | ( expression )
          

binop: + | - | * | % | / | >> | << | > | < | >= | <= | == | != | = | & | "|" | && | "||"
     

unop: ! 
    | -
              
target: object field-access*

object: NAME
      | self
      | super
      
field-access: "." NAME
            | "[" expression "]"
                       
              
              
type: native-type
    | userdefined-type
    
native-type: int
           | num
           | char
           | string
           | bool         

=head3 M1 Semantic rules


=head2 References

[1] PDD 32: M0 Design Spec

[2] Paris Avgeriou and Uwe Zdun, Architectural Patterns Revisited - A Pattern Language
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.141.7444&rep=rep1&type=pdf

[3] http://www.dwheeler.com/sloccount/

=cut

__END__
Local Variables:
  fill-column:78
End:
